# -*- coding: utf-8 -*-
"""Season Variations_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNwxXMfG8Vzd-1GnDXRjGe3TYIvTWufW
"""

import numpy as np
import matplotlib.pyplot as plt
import math as m
from numpy import *

def flux(d=0,l=0,R=6e6,a=1.4955e11,e=0.016,Lu=4e26,hr=12):
  l=pi*l/180
  d=2*pi*d/365
  phi=(hr-12)*2*pi/24
  f=Lu/((4*pi)*(((a)*(1-(e*e))/((1+(e*cos(d)))))**2))
  TSI=f*((cos(l)*(cos(-23*pi*cos(d)/180))*cos(phi))+(sin(l)*sin(-23*pi*cos(d)/180)))
  phi0=arccos(tan(l)*tan(-23*cos(d)/180))
  DSI=f*((cos(l)*(cos(-23*pi*cos(d)/180))*sin(phi0))+(phi0*sin(l)*sin(-23*pi*cos(d)/180)))/pi
  RDSI=((cos(l)*(cos(-23*pi*cos(d)/180))*sin(phi0))+(phi0*sin(l)*sin(-23*pi*cos(d)/180)))/pi
  return [TSI,DSI,RDSI]

d=np.arange(1,720,365/720)
l=np.arange(-np.pi/2,np.pi/2,np.pi/720)
# Generate combination of grids
X, Y = np.meshgrid(d, l)

Z = flux(d=X, l=Y)[0]
# Draw rectangular contour plot
fig, ax = plt.subplots()
CS=plt.contour(X, Y*180/np.pi, Z, cmap='jet')
ax.clabel(CS, CS.levels, inline=True, fontsize=10)
plt.xlabel("Days",loc="center")
plt.ylabel("Lattitude",loc="center")
plt.title("TSI")

# plots 2 graphs in one chart
fig, fillplot = plt.subplots(1, 1)

# Mathematical function for contour
grid_ofZ = flux(d=X,l=Y)[0]

# plots contour lines
fillplot.contourf(X, Y*180/np.pi, grid_ofZ, cmap='jet')
fillplot.set_title('TSI')
fillplot.set_xlabel('DAYS')
fillplot.set_ylabel('Lattitude')

plt.show()

d=np.arange(1,720,365/720)
l=np.arange(-np.pi/2,np.pi/2,np.pi/720)
# Generate combination of grids
X, Y = np.meshgrid(d, l)

Z = flux(d=X, l=Y)[1]
# Draw rectangular contour plot
fig, ax = plt.subplots()
CS=plt.contour(X, Y*180/np.pi, Z, cmap='jet')
ax.clabel(CS, CS.levels, inline=True, fontsize=10)
plt.xlabel("Days",loc="center")
plt.ylabel("Lattitude",loc="center")
plt.title("DSI")

# plots 2 graphs in one chart
fig, fillplot = plt.subplots(1, 1)

# Mathematical function for contour
grid_ofZ = flux(d=X,l=Y)[2]

# plots contour lines
fillplot.contourf(X, Y*180/np.pi, grid_ofZ, cmap='jet')
fillplot.set_title('DSI')
fillplot.set_xlabel('Days')
fillplot.set_ylabel('Lattitude')

plt.show()

d=np.arange(1,720,365/720)
l=np.arange(-np.pi/2,np.pi/2,np.pi/720)
# Generate combination of grids
X, Y = np.meshgrid(d, l)

Z = flux(d=X, l=Y)[2]
# Draw rectangular contour plot
fig, ax = plt.subplots(1,1)
CS=plt.contour(X, Y*180/np.pi, Z, cmap='jet')
ax.clabel(CS, CS.levels, inline=True, fontsize=10)
plt.xlabel("Days",loc="center")
plt.ylabel("Lattitude",loc="center")
plt.title("RDSI")

# plots 2 graphs in one chart
fig, fillplot = plt.subplots(1, 1)

# Mathematical function for contour
grid_ofZ = flux(d=X,l=Y)[2]

# plots contour lines
fillplot.contourf(X, Y*180/np.pi, grid_ofZ, cmap='jet')
fillplot.set_title('RDSI')
fillplot.set_xlabel('Days')
fillplot.set_ylabel('Lattitude')

plt.show()